const data = {
  errcode: 0,
  errmsg: null,
  data: [
    {
      discoveryContentType: 9,
      data: {
        iconTag: null,
        productPrice: 290,
        priceTipBadge: {
          type: 0,
          text: '已减¥65',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 44173741,
        houseName:
          '【踏春出游季•绿野仙踪】情侣静谧情调小窝•智能大屏投影•沙面公园•夜游珠江•朝拜圣心大教堂',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/landlordunit/day_200728/thumb/202007281552537926_360_480.jpg',
          width: 360,
          height: 480,
        },
        commentScore: '4.8',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·1居1床 2人 4.8分',
        showHouseVideo: false,
        cityId: 45,
        finalPrice: 225,
        location: '广州·荔湾区',
      },
    },
    {
      discoveryContentType: 3,
      data: {
        iconTag: null,
        productPrice: 218,
        priceTipBadge: {
          type: 0,
          text: '已减¥63',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 51953704,
        houseName: '米朵国际公寓(广州沙涌地铁站店)雅致大床房',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/cunit/day_210909/thumb/202109091308301691_700_467.jpg',
          width: 700,
          height: 467,
        },
        commentScore: '4.7',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·1居1床 2人 4.7分',
        showHouseVideo: false,
        cityId: 45,
        finalPrice: 155,
        location: '广州·荔湾区',
      },
    },
    {
      discoveryContentType: 9,
      data: {
        iconTag: null,
        productPrice: 1403,
        priceTipBadge: {
          type: 0,
          text: '已减¥219',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 18298295,
        houseName:
          '进出方便【日式风雅颂】琶洲派对复式6床|广交会国际展馆2km|求婚生日会商务|麻将火锅投影足球机',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/landlordunit/day_191218/thumb/201912181440563294_360_480.jpg',
          width: 360,
          height: 480,
        },
        commentScore: '4.8',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·5居6床 12人 4.8分',
        showHouseVideo: false,
        cityId: 45,
        finalPrice: 1184,
        location: '广州·海珠区',
      },
    },
    {
      discoveryContentType: 9,
      data: {
        iconTag: null,
        productPrice: 273,
        priceTipBadge: {
          type: 0,
          text: '已减¥48',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 20061007,
        houseName: '雅致中国风大床房/南站免费接送/近长隆/可开票',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/landlordunit/day_200105/thumb/202001051429207308_360_480.jpg',
          width: 360,
          height: 480,
        },
        commentScore: '4.9',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·1居1床 2人 4.9分',
        showHouseVideo: false,
        cityId: 45,
        finalPrice: 225,
        location: '广州·番禺区',
      },
    },
    {
      discoveryContentType: 9,
      data: {
        iconTag: null,
        productPrice: 196,
        priceTipBadge: {
          type: 0,
          text: '已减¥37',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 12731258,
        houseName:
          '{徒者-短租便宜}  上下九步行街 | 北京路商圈 | 珠江夜游永庆坊 | 地铁口清新投影会员房',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/landlordunit/day_190612/thumb/201906121047444344_360_480.jpg',
          width: 360,
          height: 480,
        },
        commentScore: '4.7',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·1居1床 2人 4.7分',
        showHouseVideo: true,
        cityId: 45,
        finalPrice: 159,
        location: '广州·荔湾区',
      },
    },
    {
      discoveryContentType: 9,
      data: {
        iconTag: null,
        productPrice: 1005,
        priceTipBadge: {
          type: 0,
          text: '已减¥317',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 13196128,
        houseName:
          '【贰号公馆】独栋三层5房/自动麻将投影桌游/上下九荔湾广场旁/永庆坊沙面十三行/西关地道美食',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/landlordunit/day_190615/thumb/201906151731475951_360_480.jpg',
          width: 360,
          height: 480,
        },
        commentScore: '5.0',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·5居5床 10人 5.0分',
        showHouseVideo: false,
        cityId: 45,
        finalPrice: 688,
        location: '广州·荔湾区',
      },
    },
    {
      discoveryContentType: 9,
      data: {
        iconTag: null,
        productPrice: 415,
        priceTipBadge: {
          type: 0,
          text: '已减¥97',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 8465745,
        houseName: '西关里珠玑—具有西关原汁原味特色民宿',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/landlordunit/day_190723/thumb/201907230818439048_360_480.jpg',
          width: 360,
          height: 480,
        },
        commentScore: '5.0',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·1居1床 2人 5.0分',
        showHouseVideo: true,
        cityId: 45,
        finalPrice: 318,
        location: '广州·荔湾区',
      },
    },
    {
      discoveryContentType: 9,
      data: {
        iconTag: null,
        productPrice: 207,
        priceTipBadge: {
          type: 0,
          text: '已减¥38',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 49139347,
        houseName: '近商圈近医院温馨私享Loft复式大窗房',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/qualifiedpics/day_210822/thumb/202108222250217737_360_480.jpg',
          width: 360,
          height: 480,
        },
        commentScore: '4.0',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·1居1床 2人 4.0分',
        showHouseVideo: true,
        cityId: 45,
        finalPrice: 169,
        location: '广州·天河区',
      },
    },
    {
      discoveryContentType: 9,
      data: {
        iconTag: null,
        productPrice: 143,
        priceTipBadge: {
          type: 0,
          text: '已减¥26',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 51830434,
        houseName:
          '豪华落地Loft复式大床房（近地铁，近白云汇广场，国际会议中心)',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/landlordunit/day_210901/thumb/202109011942432508_360_480.jpg',
          width: 360,
          height: 480,
        },
        commentScore: '4.6',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·1居1床 2人 4.6分',
        showHouseVideo: false,
        cityId: 45,
        finalPrice: 117,
        location: '广州·白云区',
      },
    },
    {
      discoveryContentType: 9,
      data: {
        iconTag: null,
        productPrice: 598,
        priceTipBadge: {
          type: 0,
          text: '已减¥158',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 40157566,
        houseName:
          'Loft复式温馨三房临近沙面上下九永庆坊旅游区&北京路步行街地铁便捷到达',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/landlordunit/day_210517/thumb/202105171125117829_360_480.jpg',
          width: 360,
          height: 480,
        },
        commentScore: '5.0',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·3居3床 6人 5.0分',
        showHouseVideo: false,
        cityId: 45,
        finalPrice: 440,
        location: '广州·荔湾区',
      },
    },
    {
      discoveryContentType: 3,
      data: {
        iconTag: null,
        productPrice: 273,
        priceTipBadge: {
          type: 0,
          text: '已减¥65',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 5772636,
        houseName:
          'LOFT双床房55寸大电视适合十三行进货北京路上下九游玩近孙逸仙纪念医院广州医科大附属一院（非江景）',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/landlordunit/day_180902/thumb/201809021105384480_700_467.jpg',
          width: 700,
          height: 467,
        },
        commentScore: '4.4',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·1居2床 4人 4.4分',
        showHouseVideo: true,
        cityId: 45,
        finalPrice: 208,
        location: '广州·越秀区',
      },
    },
    {
      discoveryContentType: 9,
      data: {
        iconTag: null,
        productPrice: 1352,
        priceTipBadge: {
          type: 0,
          text: '已减¥258',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 52040560,
        houseName:
          '进出方便【炫彩乌托邦】琶洲聚会party200平复式|可住12人|麻将游戏机投影|广交会展馆2km|',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/landlordunit/day_210902/thumb/202109022133235468_360_480.jpg',
          width: 360,
          height: 480,
        },
        commentScore: '5.0',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·4居6床 12人 5.0分',
        showHouseVideo: false,
        cityId: 45,
        finalPrice: 1094,
        location: '广州·海珠区',
      },
    },
    {
      discoveryContentType: 3,
      data: {
        iconTag: null,
        productPrice: 208,
        priceTipBadge: {
          type: 0,
          text: '已减¥48',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 47680507,
        houseName:
          '智简民宿A/中大/广外/gogo新天地/AI加持/自助手工咖啡/大屏电视',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/landlordunit/day_210814/thumb/202108141259229162_700_467.jpg',
          width: 700,
          height: 467,
        },
        commentScore: '4.5',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·1居1床 2人 4.5分',
        showHouseVideo: true,
        cityId: 45,
        finalPrice: 160,
        location: '广州·番禺区',
      },
    },
    {
      discoveryContentType: 9,
      data: {
        iconTag: null,
        productPrice: 407,
        priceTipBadge: {
          type: 0,
          text: '已减¥78',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 45332023,
        houseName: '【唯梵•风之谷】沙面|上下九|西关复式两居',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/landlordunit/day_201001/thumb/202010011530588874_360_480.jpg',
          width: 360,
          height: 480,
        },
        commentScore: '4.9',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·2居2床 4人 4.9分',
        showHouseVideo: false,
        cityId: 45,
        finalPrice: 329,
        location: '广州·荔湾区',
      },
    },
    {
      discoveryContentType: 9,
      data: {
        iconTag: null,
        productPrice: 364,
        priceTipBadge: {
          type: 0,
          text: '已减¥64',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 13283950,
        houseName: '广州塔/近地铁/广交会/珠江夜游/浴缸',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/landlordunit/day_190626/thumb/201906261634059454_360_480.jpg',
          width: 360,
          height: 480,
        },
        commentScore: '4.9',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·1居1床 2人 4.9分',
        showHouseVideo: false,
        cityId: 45,
        finalPrice: 300,
        location: '广州·海珠区',
      },
    },
    {
      discoveryContentType: 9,
      data: {
        iconTag: null,
        productPrice: 324,
        priceTipBadge: {
          type: 0,
          text: '已减¥105',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 40404708,
        houseName: '地铁6号沙贝站/近北京路万达/江景公寓',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/landlordunit/day_200620/thumb/202006201637368526_360_480.jpg',
          width: 360,
          height: 480,
        },
        commentScore: '4.5',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·2居2床 3人 4.5分',
        showHouseVideo: true,
        cityId: 45,
        finalPrice: 219,
        location: '广州·白云区',
      },
    },
    {
      discoveryContentType: 9,
      data: {
        iconTag: null,
        productPrice: 474,
        priceTipBadge: {
          type: 0,
          text: '已减¥87',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 15653268,
        houseName:
          '〖翡冷翠〗加勒比庄园LOFT/行李寄存/全身镜/宽屏投影/5分钟到珠江新城地铁站/步行K11、花城汇',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/landlordunit/day_191128/thumb/201911281857137020_360_480.jpg',
          width: 360,
          height: 480,
        },
        commentScore: '4.9',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·1居1床 2人 4.9分',
        showHouseVideo: false,
        cityId: 45,
        finalPrice: 387,
        location: '广州·天河区',
      },
    },
    {
      discoveryContentType: 3,
      data: {
        iconTag: null,
        productPrice: 490,
        priceTipBadge: {
          type: 0,
          text: '已减¥46',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 49870042,
        houseName:
          '〖意途·陆〗带厨房可做饭 简约现代风   两居室 大床房 珠江新城 直达长隆可寄存行李',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/landlordunit/day_210508/thumb/202105081855312851_700_467.jpg',
          width: 700,
          height: 467,
        },
        commentScore: '4.7',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·2居2床 4人 4.7分',
        showHouseVideo: true,
        cityId: 45,
        finalPrice: 444,
        location: '广州·天河区',
      },
    },
    {
      discoveryContentType: 9,
      data: {
        iconTag: null,
        productPrice: 355,
        priceTipBadge: {
          type: 0,
          text: '已减¥64',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 51858142,
        houseName:
          '广州塔江景房  ｜巨幕投影| 夕阳灯｜海心沙｜海心桥｜琶洲广交会、珠江新城。',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/landlordunit/day_210819/thumb/202108192131269043_360_480.jpg',
          width: 360,
          height: 480,
        },
        commentScore: '4.8',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·1居1床 2人 4.8分',
        showHouseVideo: false,
        cityId: 45,
        finalPrice: 291,
        location: '广州·海珠区',
      },
    },
    {
      discoveryContentType: 3,
      data: {
        iconTag: null,
        productPrice: 227,
        priceTipBadge: {
          type: 0,
          text: '已减¥40',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 52096417,
        houseName: '悦趣服务式公寓轻奢大床房',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/cunit/day_210907/thumb/202109071455223002_700_467.jpg',
          width: 700,
          height: 467,
        },
        commentScore: '4.8',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·1居1床 2人 4.8分',
        showHouseVideo: false,
        cityId: 45,
        finalPrice: 187,
        location: '广州·黄埔区',
      },
    },
    {
      discoveryContentType: 3,
      data: {
        iconTag: null,
        productPrice: 198,
        priceTipBadge: {
          type: 0,
          text: '已减¥35',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 14768489,
        houseName: '【梅花园】森系物语·广州东站/吊椅一居室',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/qualifiedpics/day_190829/thumb/201908291708358385_700_467.jpg',
          width: 700,
          height: 467,
        },
        commentScore: '4.6',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·1居1床 2人 4.6分',
        showHouseVideo: false,
        cityId: 45,
        finalPrice: 163,
        location: '广州·天河区',
      },
    },
    {
      discoveryContentType: 9,
      data: {
        iconTag: null,
        productPrice: 363,
        priceTipBadge: {
          type: 0,
          text: '已减¥17',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 48672772,
        houseName:
          '  【哇小屋·小布丁】珠江新城韩风ins奶油风1.8大床网红日落灯投影仪/美领馆广州塔机场火车站长隆',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/landlordunit/day_210428/thumb/202104281948573791_360_480.jpg',
          width: 360,
          height: 480,
        },
        commentScore: '4.9',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·1居1床 2人 4.9分',
        showHouseVideo: false,
        cityId: 45,
        finalPrice: 346,
        location: '广州·天河区',
      },
    },
    {
      discoveryContentType: 3,
      data: {
        iconTag: null,
        productPrice: 285,
        priceTipBadge: {
          type: 0,
          text: '已减¥63',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 123331,
        houseName:
          '豪华街景大床房天字码头长提酒吧街珠江夜游，近十三行国际服装城，新中国大厦，石室圣心大教堂，',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/qualifiedpics/day_170807/thumb/201708071708433461_700_467.jpg',
          width: 700,
          height: 467,
        },
        commentScore: '4.5',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·1居1床 2人 4.5分',
        showHouseVideo: true,
        cityId: 45,
        finalPrice: 222,
        location: '广州·越秀区',
      },
    },
    {
      discoveryContentType: 9,
      data: {
        iconTag: null,
        productPrice: 456,
        priceTipBadge: {
          type: 0,
          text: '已减¥87',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 14870878,
        houseName:
          '高质感 ·浪漫情调贝尔格莱德·梦幻摇曳烛光影院/行李寄存/美签英签/直达机场/散步珠江边',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/landlordunit/day_191113/thumb/201911131537505956_360_480.jpg',
          width: 360,
          height: 480,
        },
        commentScore: '4.9',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·1居1床 2人 4.9分',
        showHouseVideo: true,
        cityId: 45,
        finalPrice: 369,
        location: '广州·天河区',
      },
    },
    {
      discoveryContentType: 3,
      data: {
        iconTag: null,
        productPrice: 262,
        priceTipBadge: {
          type: 0,
          text: '已减¥25',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 48540133,
        houseName: '润亭酒店式公寓润悦大床房（免费停车）',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/cunit/day_210402/thumb/202104020946486743_700_467.jpeg',
          width: 700,
          height: 467,
        },
        commentScore: '4.8',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·1居1床 2人 4.8分',
        showHouseVideo: true,
        cityId: 45,
        finalPrice: 237,
        location: '广州·海珠区',
      },
    },
    {
      discoveryContentType: 9,
      data: {
        iconTag: null,
        productPrice: 313,
        priceTipBadge: {
          type: 0,
          text: '已减¥83',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 45719386,
        houseName:
          '朴素|嘉禾地铁|复式loft|情侣约会|白云新城|云门PARK|近中院、白云山|高清电|直达机场',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/landlordunit/day_200925/thumb/202009251445383761_360_480.jpg',
          width: 360,
          height: 480,
        },
        commentScore: '4.9',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·1居1床 2人 4.9分',
        showHouseVideo: false,
        cityId: 45,
        finalPrice: 230,
        location: '广州·白云区',
      },
    },
    {
      discoveryContentType: 9,
      data: {
        iconTag: null,
        productPrice: 427,
        priceTipBadge: {
          type: 0,
          text: '已减¥75',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 454607,
        houseName: '消毒/长租特惠【逐梦】地铁站上盖/太古汇',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/landlordunit/day_210906/thumb/202109061405284204_360_480.jpg',
          width: 360,
          height: 480,
        },
        commentScore: '4.9',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·1居1床 1人 4.9分',
        showHouseVideo: false,
        cityId: 45,
        finalPrice: 352,
        location: '广州·天河区',
      },
    },
    {
      discoveryContentType: 9,
      data: {
        iconTag: null,
        productPrice: 803,
        priceTipBadge: {
          type: 0,
          text: '已减¥152',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 40426233,
        houseName: '广州长隆景区•大滑梯波波池游乐房•南站•叁',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/landlordunit/day_200909/thumb/202009091357147996_360_480.jpg',
          width: 360,
          height: 480,
        },
        commentScore: '4.9',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·2居3床 6人 4.9分',
        showHouseVideo: false,
        cityId: 45,
        finalPrice: 651,
        location: '广州·番禺区',
      },
    },
    {
      discoveryContentType: 9,
      data: {
        iconTag: null,
        productPrice: 304,
        priceTipBadge: {
          type: 0,
          text: '已减¥80',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 19174429,
        houseName:
          '流年|复式loft|嘉禾双地铁|白云新城|广州塔|云门|近中院、八院、白云山|高清电视|直达机场',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/landlordunit/day_191228/thumb/201912281750357747_360_480.jpg',
          width: 360,
          height: 480,
        },
        commentScore: '5.0',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·1居1床 2人 5.0分',
        showHouseVideo: false,
        cityId: 45,
        finalPrice: 224,
        location: '广州·白云区',
      },
    },
    {
      discoveryContentType: 9,
      data: {
        iconTag: null,
        productPrice: 312,
        priceTipBadge: {
          type: 0,
          text: '已减¥60',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 12405338,
        houseName: '豪华复式大床套房☞汉溪长隆地铁站店/近长隆欢乐世界/近美食街',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/landlordunit/day_190523/thumb/201905231758125316_360_480.jpg',
          width: 360,
          height: 480,
        },
        commentScore: '4.8',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·1居1床 2人 4.8分',
        showHouseVideo: false,
        cityId: 45,
        finalPrice: 252,
        location: '广州·番禺区',
      },
    },
    {
      discoveryContentType: 9,
      data: {
        iconTag: null,
        productPrice: 223,
        priceTipBadge: {
          type: 0,
          text: '已减¥32',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 1054319,
        houseName: '穗馆 独栋 上下九 沙面 北京路 带天台',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/landlordunit/day_191223/thumb/201912231022153331_360_480.jpg',
          width: 360,
          height: 480,
        },
        commentScore: '4.9',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·1居1床 2人 4.9分',
        showHouseVideo: false,
        cityId: 45,
        finalPrice: 191,
        location: '广州·荔湾区',
      },
    },
    {
      discoveryContentType: 9,
      data: {
        iconTag: null,
        productPrice: 288,
        priceTipBadge: {
          type: 0,
          text: '已减¥78',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 46836829,
        houseName:
          '乐家②ins北欧风#中山二院孙逸仙纪念医院#广医一院#北京路步行街#上下九/沙面/永庆坊/新荔枝湾涌',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/qualifiedpics/day_201208/thumb/202012080020028345_360_480.jpg',
          width: 360,
          height: 480,
        },
        commentScore: '4.8',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·1居1床 2人 4.8分',
        showHouseVideo: true,
        cityId: 45,
        finalPrice: 210,
        location: '广州·越秀区',
      },
    },
    {
      discoveryContentType: 9,
      data: {
        iconTag: null,
        productPrice: 390,
        priceTipBadge: {
          type: 0,
          text: '已减¥75',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 53422897,
        houseName:
          '无墅文旅/温暖复式大床房/一房一厅/浪漫情侣/免费投影/可投屏/做饭/长租/全屋消毒/一客一换',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/landlordunit/day_211223/thumb/202112231331126833_360_480.jpg',
          width: 360,
          height: 480,
        },
        commentScore: '5.0',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·1居1床 2人 5.0分',
        showHouseVideo: false,
        cityId: 45,
        finalPrice: 315,
        location: '广州·番禺区',
      },
    },
    {
      discoveryContentType: 3,
      data: {
        iconTag: null,
        productPrice: 140,
        priceTipBadge: {
          type: 0,
          text: '已减¥33',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 40341449,
        houseName: '智简民宿（标配）广工/广美/自助手工咖啡/AI加',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/landlordunit/day_200618/thumb/202006181425153041_700_467.jpg',
          width: 700,
          height: 467,
        },
        commentScore: '4.7',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·1居1床 2人 4.7分',
        showHouseVideo: true,
        cityId: 45,
        finalPrice: 107,
        location: '广州·番禺区',
      },
    },
    {
      discoveryContentType: 9,
      data: {
        iconTag: null,
        productPrice: 369,
        priceTipBadge: {
          type: 0,
          text: '已减¥51',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 5018974,
        houseName:
          '3/7汉溪长隆站/琶洲会展广交会/南站/野生动物园/欢乐世界/大学城/私人影院3D蓝牙/豪华家庭套房',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/landlordunit/day_200902/thumb/202009021627208939_360_480.jpg',
          width: 360,
          height: 480,
        },
        commentScore: '4.9',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·1居3床 4人 4.9分',
        showHouseVideo: true,
        cityId: 45,
        finalPrice: 318,
        location: '广州·番禺区',
      },
    },
    {
      discoveryContentType: 9,
      data: {
        iconTag: null,
        productPrice: 777,
        priceTipBadge: {
          type: 0,
          text: '已减¥138',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 39524031,
        houseName:
          '复式loft大床/可长租/广州塔/保利中达广场/天空别墅/猎德A出口/珠江新城/近地铁5号线',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/landlordunit/day_200606/thumb/202006060123037655_360_480.jpg',
          width: 360,
          height: 480,
        },
        commentScore: '4.8',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·1居1床 2人 4.8分',
        showHouseVideo: false,
        cityId: 45,
        finalPrice: 639,
        location: '广州·天河区',
      },
    },
    {
      discoveryContentType: 9,
      data: {
        iconTag: null,
        productPrice: 327,
        priceTipBadge: {
          type: 0,
          text: '已减¥93',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 51733390,
        houseName:
          'Vilo轻奢投影落地窗大床房 长隆欢乐世界·番禺万达广场·南村万博地铁站·广州南站',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/landlordunit/day_210806/thumb/202108061353433277_360_480.jpg',
          width: 360,
          height: 480,
        },
        commentScore: '4.5',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·1居1床 2人 4.5分',
        showHouseVideo: false,
        cityId: 45,
        finalPrice: 234,
        location: '广州·番禺区',
      },
    },
    {
      discoveryContentType: 3,
      data: {
        iconTag: null,
        productPrice: 492,
        priceTipBadge: {
          type: 0,
          text: '已减¥90',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 14165915,
        houseName: '正佳复式双床房天河CBD珠江新城K11',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/landlordunit/day_200708/thumb/202007081751018778_700_467.jpg',
          width: 700,
          height: 467,
        },
        commentScore: '4.8',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·1居2床 4人 4.8分',
        showHouseVideo: false,
        cityId: 45,
        finalPrice: 402,
        location: '广州·天河区',
      },
    },
    {
      discoveryContentType: 9,
      data: {
        iconTag: null,
        productPrice: 1068,
        priceTipBadge: {
          type: 0,
          text: '已减¥334',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 6118996,
        houseName: '广州长隆地铁香美园复式公寓',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/qualifiedpics/day_181126/thumb/201811260808426457_360_480.jpg',
          width: 360,
          height: 480,
        },
        commentScore: '5.0',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·3居3床 6人 5.0分',
        showHouseVideo: true,
        cityId: 45,
        finalPrice: 734,
        location: '广州·番禺区',
      },
    },
    {
      discoveryContentType: 9,
      data: {
        iconTag: null,
        productPrice: 441,
        priceTipBadge: {
          type: 0,
          text: '已减¥84',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 48417853,
        houseName:
          '『白羊座』【贵族骑士】长隆对面/Loft复式低奢2床可住4人/商业拍摄/投影/浴缸/设计风格圣大公馆',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/landlordunit/day_210316/thumb/202103161602217977_360_480.jpg',
          width: 360,
          height: 480,
        },
        commentScore: '5.0',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·1居2床 4人 5.0分',
        showHouseVideo: false,
        cityId: 45,
        finalPrice: 357,
        location: '广州·番禺区',
      },
    },
    {
      discoveryContentType: 9,
      data: {
        iconTag: null,
        productPrice: 200,
        priceTipBadge: {
          type: 0,
          text: '已减¥29',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 48317083,
        houseName:
          '「崎观浅暖」广州白云机场旁广州翼文旅小镇日式风景房/向景区/地铁高增D出口/宫崎公寓',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/landlordunit/day_210224/thumb/202102241034085207_360_480.png',
          width: 360,
          height: 480,
        },
        commentScore: '4.9',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·1居1床 2人 4.9分',
        showHouseVideo: false,
        cityId: 45,
        finalPrice: 171,
        location: '广州·白云区',
      },
    },
    {
      discoveryContentType: 9,
      data: {
        iconTag: null,
        productPrice: 361,
        priceTipBadge: {
          type: 0,
          text: '已减¥64',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 52629640,
        houseName:
          '广州塔江景房｜原木风 巨幕投影 网红夕阳灯 ｜珠江新城 海心沙 海心桥 琶洲会展馆',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/landlordunit/day_211101/thumb/202111010102176638_360_480.jpg',
          width: 360,
          height: 480,
        },
        commentScore: '4.9',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·1居1床 2人 4.9分',
        showHouseVideo: false,
        cityId: 45,
        finalPrice: 297,
        location: '广州·海珠区',
      },
    },
    {
      discoveryContentType: 3,
      data: {
        iconTag: null,
        productPrice: 162,
        priceTipBadge: {
          type: 0,
          text: '已减¥57',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 13295815,
        houseName:
          '广州南站馨园小筑限时特价大床房（南站专车免费接送-机打发票）',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/landlordunit/day_211111/thumb/202111110029374547_700_467.jpg',
          width: 700,
          height: 467,
        },
        commentScore: '4.9',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·1居1床 2人 4.9分',
        showHouseVideo: false,
        cityId: 45,
        finalPrice: 105,
        location: '广州·番禺区',
      },
    },
    {
      discoveryContentType: 3,
      data: {
        iconTag: null,
        productPrice: 253,
        priceTipBadge: {
          type: 0,
          text: '已减¥46',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 52615393,
        houseName:
          '树根书屋时尚简约公寓，落地窗，单间户型，高品质家具，共享私家花香大院。',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/landlordunit/day_211028/thumb/202110281606475489_700_467.jpg',
          width: 700,
          height: 467,
        },
        commentScore: '4.7',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·1居1床 2人 4.7分',
        showHouseVideo: false,
        cityId: 45,
        finalPrice: 207,
        location: '广州·海珠区',
      },
    },
    {
      discoveryContentType: 9,
      data: {
        iconTag: null,
        productPrice: 313,
        priceTipBadge: {
          type: 0,
          text: '已减¥57',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 52255153,
        houseName:
          '越秀城景新中式双床房/团一大地铁站/北京路/珠江夜游/海珠广场/沙面/上下九/广州塔/',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/landlordunit/day_210918/thumb/202109181321569849_360_480.jpg',
          width: 360,
          height: 480,
        },
        commentScore: '5.0',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·1居2床 4人 5.0分',
        showHouseVideo: false,
        cityId: 45,
        finalPrice: 256,
        location: '广州·越秀区',
      },
    },
    {
      discoveryContentType: 9,
      data: {
        iconTag: null,
        productPrice: 310,
        priceTipBadge: {
          type: 0,
          text: '已减¥70',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 53281663,
        houseName:
          '4K巨幕投影游戏机大床房一德路/北京路/孙逸仙医院/十三行/广医医院/中山二院/海珠广场/珠江边',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/landlordunit/day_211203/thumb/202112031055474902_360_480.jpg',
          width: 360,
          height: 480,
        },
        commentScore: '5.0',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·1居1床 2人 5.0分',
        showHouseVideo: true,
        cityId: 45,
        finalPrice: 240,
        location: '广州·越秀区',
      },
    },
    {
      discoveryContentType: 9,
      data: {
        iconTag: null,
        productPrice: 572,
        priceTipBadge: {
          type: 0,
          text: '已减¥125',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 12460337,
        houseName: '简约宜家风&临近北京路天字码头海珠广场温',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/landlordunit/day_190525/thumb/201905251840218433_360_480.jpg',
          width: 360,
          height: 480,
        },
        commentScore: '4.8',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·2居2床 4人 4.8分',
        showHouseVideo: false,
        cityId: 45,
        finalPrice: 447,
        location: '广州·越秀区',
      },
    },
    {
      discoveryContentType: 3,
      data: {
        iconTag: null,
        productPrice: 205,
        priceTipBadge: {
          type: 0,
          text: '已减¥38',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 49906519,
        houseName: '近商圈近医院温馨私享Loft复式',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/qualifiedpics/day_210822/thumb/202108222256567278_700_467.jpg',
          width: 700,
          height: 467,
        },
        commentScore: '4.4',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·1居1床 2人 4.4分',
        showHouseVideo: true,
        cityId: 45,
        finalPrice: 167,
        location: '广州·天河区',
      },
    },
    {
      discoveryContentType: 9,
      data: {
        iconTag: null,
        productPrice: 333,
        priceTipBadge: {
          type: 0,
          text: '已减¥44',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 5270946,
        houseName: '浪漫商务房',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/landlordunit/day_180810/thumb/201808101923494689_360_480.jpg',
          width: 360,
          height: 480,
        },
        commentScore: '5.0',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·1居1床 2人 5.0分',
        showHouseVideo: false,
        cityId: 45,
        finalPrice: 289,
        location: '广州·天河区',
      },
    },
    {
      discoveryContentType: 9,
      data: {
        iconTag: null,
        productPrice: 440,
        priceTipBadge: {
          type: 0,
          text: '已减¥170',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 16187004,
        houseName: '广州南站/可洗衣做饭/长隆十分钟/大学城/轻奢两居',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/qualifiedpics/day_191124/thumb/201911241709186360_360_480.jpg',
          width: 360,
          height: 480,
        },
        commentScore: '4.9',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·2居2床 4人 4.9分',
        showHouseVideo: false,
        cityId: 45,
        finalPrice: 270,
        location: '广州·番禺区',
      },
    },
    {
      discoveryContentType: 9,
      data: {
        iconTag: null,
        productPrice: 782,
        priceTipBadge: {
          type: 0,
          text: '已减¥144',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 51489970,
        houseName: '广州长隆景区•家庭滑梯波波池投影两居室亲子房•贰',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/qualifiedpics/day_210802/thumb/202108021015163574_360_480.jpg',
          width: 360,
          height: 480,
        },
        commentScore: '4.8',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·2居2床 4人 4.8分',
        showHouseVideo: false,
        cityId: 45,
        finalPrice: 638,
        location: '广州·番禺区',
      },
    },
    {
      discoveryContentType: 9,
      data: {
        iconTag: null,
        productPrice: 864,
        priceTipBadge: {
          type: 0,
          text: '已减¥266',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 40396343,
        houseName:
          '全屋消毒长隆广州塔投影复式2房·光影工坊/双地铁口·近欢乐世界·大马戏·动物园·水上乐园·广州南高铁',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/landlordunit/day_200910/thumb/202009101623434871_360_480.jpg',
          width: 360,
          height: 480,
        },
        commentScore: '4.9',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·2居4床 6人 4.9分',
        showHouseVideo: false,
        cityId: 45,
        finalPrice: 598,
        location: '广州·番禺区',
      },
    },
    {
      discoveryContentType: 9,
      data: {
        iconTag: null,
        productPrice: 335,
        priceTipBadge: {
          type: 0,
          text: '已减¥95',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 48383986,
        houseName:
          '【5号停机坪】百信广场/万达广场复式两居&岗贝路一条街，自助入住独立带锁两居',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/apisunit/day_210310/thumb/202103101441598817_360_480.jpeg',
          width: 360,
          height: 480,
        },
        commentScore: '4.9',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·2居2床 4人 4.9分',
        showHouseVideo: false,
        cityId: 45,
        finalPrice: 240,
        location: '广州·白云区',
      },
    },
    {
      discoveryContentType: 9,
      data: {
        iconTag: null,
        productPrice: 652,
        priceTipBadge: {
          type: 0,
          text: '已减¥118',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 18230801,
        houseName: '广州长隆景区•轻奢风投影与55寸电视房',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/landlordunit/day_200402/thumb/202004021156063321_360_480.jpg',
          width: 360,
          height: 480,
        },
        commentScore: '4.9',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·2居2床 4人 4.9分',
        showHouseVideo: false,
        cityId: 45,
        finalPrice: 534,
        location: '广州·番禺区',
      },
    },
    {
      discoveryContentType: 3,
      data: {
        iconTag: null,
        productPrice: 105,
        priceTipBadge: {
          type: 0,
          text: '已减¥20',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 45352717,
        houseName: '消毒/广州南站专车接站  One Day设计甄选大床房ཧ',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/landlordunit/day_210125/thumb/202101251304582768_700_467.jpg',
          width: 700,
          height: 467,
        },
        commentScore: '4.7',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·1居1床 2人 4.7分',
        showHouseVideo: false,
        cityId: 45,
        finalPrice: 85,
        location: '广州·番禺区',
      },
    },
    {
      discoveryContentType: 9,
      data: {
        iconTag: null,
        productPrice: 222,
        priceTipBadge: {
          type: 0,
          text: '已减¥42',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 45251086,
        houseName:
          '[徒者-短租便宜] 上下九商圈 | 北京路 | 陈家祠地铁口 | 永庆坊 |  投影会员',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/qualifiedpics/day_200908/thumb/202009081833523789_360_480.jpg',
          width: 360,
          height: 480,
        },
        commentScore: '4.7',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·1居1床 2人 4.7分',
        showHouseVideo: true,
        cityId: 45,
        finalPrice: 180,
        location: '广州·荔湾区',
      },
    },
    {
      discoveryContentType: 9,
      data: {
        iconTag: null,
        productPrice: 676,
        priceTipBadge: {
          type: 0,
          text: '已减¥180',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 51924760,
        houseName:
          '【北邻江景】超大落地窗珠江夜游江湾大桥全线江景近6号线近商圈温馨私享大客厅卧江入眠网红打卡软装',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/landlordunit/day_210826/thumb/202108262103051209_360_480.jpg',
          width: 360,
          height: 480,
        },
        commentScore: '4.9',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·1居1床 2人 4.9分',
        showHouseVideo: false,
        cityId: 45,
        finalPrice: 496,
        location: '广州·越秀区',
      },
    },
    {
      discoveryContentType: 9,
      data: {
        iconTag: null,
        productPrice: 354,
        priceTipBadge: {
          type: 0,
          text: '已减¥115',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 53122369,
        houseName:
          'Uno复式公寓(碧桂园从化)三床房&豪华配置|从化温泉旅游区|从化客运站|从化七中|广州城建职业学院',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/landlordunit/day_211117/thumb/202111172219466588_360_480.jpg',
          width: 360,
          height: 480,
        },
        commentScore: '4.7',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·2居3床 4人 4.7分',
        showHouseVideo: true,
        cityId: 45,
        finalPrice: 239,
        location: '广州·从化区',
      },
    },
    {
      discoveryContentType: 9,
      data: {
        iconTag: null,
        productPrice: 302,
        priceTipBadge: {
          type: 0,
          text: '已减¥57',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 46605901,
        houseName:
          '越秀城景大床/团一大地铁站300米/近北京路海珠广场十三行/中山一院/省人民医院/（风格随机安排）',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/landlordunit/day_210116/thumb/202101161221117524_360_480.jpg',
          width: 360,
          height: 480,
        },
        commentScore: '4.9',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·1居1床 2人 4.9分',
        showHouseVideo: false,
        cityId: 45,
        finalPrice: 245,
        location: '广州·越秀区',
      },
    },
    {
      discoveryContentType: 9,
      data: {
        iconTag: null,
        productPrice: 519,
        priceTipBadge: {
          type: 0,
          text: '已减¥141',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 13600021,
        houseName:
          '【卧江源】江景巨幕投影地台大床/6米临江如沉醉卧在梦中/近北京路/楼下酒吧街珠江夜游/东山口黄沙小蛮',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/landlordunit/day_191230/thumb/201912301101129285_360_480.jpg',
          width: 360,
          height: 480,
        },
        commentScore: '4.9',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·1居1床 2人 4.9分',
        showHouseVideo: true,
        cityId: 45,
        finalPrice: 378,
        location: '广州·越秀区',
      },
    },
    {
      discoveryContentType: 9,
      data: {
        iconTag: null,
        productPrice: 499,
        priceTipBadge: {
          type: 0,
          text: '已减¥110',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 22668710,
        houseName: '广州长隆北欧复式亲子泡泡吊椅情侣家庭两房',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/landlordunit/day_200708/thumb/202007081625179786_360_480.jpg',
          width: 360,
          height: 480,
        },
        commentScore: '5.0',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·2居2床 4人 5.0分',
        showHouseVideo: false,
        cityId: 45,
        finalPrice: 389,
        location: '广州·番禺区',
      },
    },
    {
      discoveryContentType: 9,
      data: {
        iconTag: null,
        productPrice: 226,
        priceTipBadge: {
          type: 0,
          text: '已减¥22',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 48265984,
        houseName:
          '【雅稚】免费车送到长隆水上乐园、欢乐世界、野生动物世界   大落地窗 秋千木马大床房',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/landlordunit/day_210208/thumb/202102082127304628_360_480.jpg',
          width: 360,
          height: 480,
        },
        commentScore: '4.7',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·1居1床 2人 4.7分',
        showHouseVideo: false,
        cityId: 45,
        finalPrice: 204,
        location: '广州·番禺区',
      },
    },
    {
      discoveryContentType: 3,
      data: {
        iconTag: null,
        productPrice: 170,
        priceTipBadge: {
          type: 0,
          text: '已减¥63',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 13295304,
        houseName: '广州南站田园风格网红民宿（南站专车免费接送）',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/landlordunit/day_190624/thumb/201906241247386465_700_467.jpg',
          width: 700,
          height: 467,
        },
        commentScore: '4.6',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·1居1床 2人 4.6分',
        showHouseVideo: false,
        cityId: 45,
        finalPrice: 107,
        location: '广州·番禺区',
      },
    },
    {
      discoveryContentType: 9,
      data: {
        iconTag: null,
        productPrice: 1011,
        priceTipBadge: {
          type: 0,
          text: '已减¥186',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 46784236,
        houseName: '灯火阑珊•长隆旁地铁边•巨幕投影麻将07',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/landlordunit/day_200917/thumb/202009170054548177_360_480.jpg',
          width: 360,
          height: 480,
        },
        commentScore: '5.0',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·3居5床 10人 5.0分',
        showHouseVideo: false,
        cityId: 45,
        finalPrice: 825,
        location: '广州·番禺区',
      },
    },
    {
      discoveryContentType: 9,
      data: {
        iconTag: null,
        productPrice: 568,
        priceTipBadge: {
          type: 0,
          text: '已减¥77',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 388021,
        houseName: '北京路步行街中式温馨三房',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/landlordunit/day_210429/thumb/202104292038072588_360_480.jpg',
          width: 360,
          height: 480,
        },
        commentScore: '4.8',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·3居3床 6人 4.8分',
        showHouseVideo: false,
        cityId: 45,
        finalPrice: 491,
        location: '广州·越秀区',
      },
    },
    {
      discoveryContentType: 3,
      data: {
        iconTag: null,
        productPrice: 197,
        priceTipBadge: {
          type: 0,
          text: '已减¥45',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 51788974,
        houseName:
          '智慧家T/华师/广大/星海/生物岛/大学城北/超大电视/自助手摇咖啡/全智能灯光/AI音箱/可开发票',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/landlordunit/day_210812/thumb/202108121850374504_700_467.jpg',
          width: 700,
          height: 467,
        },
        commentScore: '4.9',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·1居1床 2人 4.9分',
        showHouseVideo: true,
        cityId: 45,
        finalPrice: 152,
        location: '广州·番禺区',
      },
    },
    {
      discoveryContentType: 3,
      data: {
        iconTag: null,
        productPrice: 127,
        priceTipBadge: null,
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 446833,
        houseName: '广州天河华观路中万科米酷（清新简约）房',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/qualifiedpics/day_180123/thumb/201801230105398611_700_467.jpg',
          width: 700,
          height: 467,
        },
        commentScore: '4.7',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·1居1床 2人 4.7分',
        showHouseVideo: false,
        cityId: 45,
        finalPrice: 127,
        location: '广州·天河区',
      },
    },
    {
      discoveryContentType: 3,
      data: {
        iconTag: null,
        productPrice: 939,
        priceTipBadge: {
          type: 0,
          text: '已减¥168',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 39875095,
        houseName:
          '南北纵横国际公寓(广州北京路步行街金润铂宫店)复式豪华三卧套房（配备烘干洗衣机）',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/cunit/day_200617/thumb/202006170214367422_700_467.jpeg',
          width: 700,
          height: 467,
        },
        commentScore: '4.7',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·3居3床 6人 4.7分',
        showHouseVideo: true,
        cityId: 45,
        finalPrice: 771,
        location: '广州·越秀区',
      },
    },
    {
      discoveryContentType: 9,
      data: {
        iconTag: null,
        productPrice: 587,
        priceTipBadge: {
          type: 0,
          text: '已减¥63',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 39587864,
        houseName: '高层Loft视野好现代风格适合直播',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/landlordunit/day_200608/thumb/202006081019442353_360_480.jpg',
          width: 360,
          height: 480,
        },
        commentScore: '4.7',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·3居3床 6人 4.7分',
        showHouseVideo: false,
        cityId: 45,
        finalPrice: 524,
        location: '广州·荔湾区',
      },
    },
    {
      discoveryContentType: 9,
      data: {
        iconTag: null,
        productPrice: 1327,
        priceTipBadge: {
          type: 0,
          text: '已减¥236',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 48708778,
        houseName:
          '从化温泉明月山溪6房温泉别墅【超大花园+大泳池+天然流溪温泉】',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/landlordunit/day_220608/thumb/202206081341486528_360_480.jpg',
          width: 360,
          height: 480,
        },
        commentScore: '4.3',
        extendMap: { logicBit: '0' },
        summaryText: '整套·6居10床 16人 4.3分',
        showHouseVideo: false,
        cityId: 45,
        finalPrice: 1091,
        location: '广州·从化区',
      },
    },
    {
      discoveryContentType: 3,
      data: {
        iconTag: null,
        productPrice: 216,
        priceTipBadge: {
          type: 0,
          text: '已减¥38',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 52361824,
        houseName: '眠夜公寓(广州佳兆业城市广场店)眠月轻奢大床房（差旅优选）',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/cunit/day_211015/thumb/202110150230141264_700_467.jpg',
          width: 700,
          height: 467,
        },
        commentScore: '4.8',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·1居1床 2人 4.8分',
        showHouseVideo: true,
        cityId: 45,
        finalPrice: 178,
        location: '广州·黄埔区',
      },
    },
    {
      discoveryContentType: 9,
      data: {
        iconTag: null,
        productPrice: 394,
        priceTipBadge: {
          type: 0,
          text: '已减¥150',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 50984935,
        houseName:
          '[藏品•万博]长隆欢乐世界/广州南站/南村万博/万达广场/番禺天河城/高品质100寸投影雅致美宿',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/qualifiedpics/day_210624/thumb/202106242018071324_360_480.jpg',
          width: 360,
          height: 480,
        },
        commentScore: '4.9',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·1居1床 2人 4.9分',
        showHouseVideo: true,
        cityId: 45,
        finalPrice: 244,
        location: '广州·番禺区',
      },
    },
    {
      discoveryContentType: 9,
      data: {
        iconTag: null,
        productPrice: 442,
        priceTipBadge: {
          type: 0,
          text: '已减¥101',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 50166829,
        houseName: '【唯梵·镰仓半日】沙面|上下九|西关|江景复式两房',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/landlordunit/day_210526/thumb/202105261702288506_360_480.jpg',
          width: 360,
          height: 480,
        },
        commentScore: '4.8',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·2居2床 4人 4.8分',
        showHouseVideo: true,
        cityId: 45,
        finalPrice: 341,
        location: '广州·荔湾区',
      },
    },
    {
      discoveryContentType: 9,
      data: {
        iconTag: null,
        productPrice: 332,
        priceTipBadge: {
          type: 0,
          text: '已减¥47',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 18442537,
        houseName: '合生广场轻奢一居室/近广州塔/',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/landlordunit/day_191221/thumb/201912211618366952_360_480.jpg',
          width: 360,
          height: 480,
        },
        commentScore: '5.0',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·1居1床 2人 5.0分',
        showHouseVideo: false,
        cityId: 45,
        finalPrice: 285,
        location: '广州·海珠区',
      },
    },
    {
      discoveryContentType: 9,
      data: {
        iconTag: null,
        productPrice: 476,
        priceTipBadge: {
          type: 0,
          text: '已减¥105',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 48878212,
        houseName:
          '【设计师的家】古色情侣房|近长隆欢乐世界|水上乐园|地铁旁带阳台|现代中式风',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/landlordunit/day_210419/thumb/202104191109506578_360_480.jpg',
          width: 360,
          height: 480,
        },
        commentScore: '4.9',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·1居1床 2人 4.9分',
        showHouseVideo: false,
        cityId: 45,
        finalPrice: 371,
        location: '广州·番禺区',
      },
    },
    {
      discoveryContentType: 9,
      data: {
        iconTag: null,
        productPrice: 453,
        priceTipBadge: {
          type: 0,
          text: '已减¥80',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 17097837,
        houseName: '泉之韵望谷温泉国际公寓+内置温泉养生汤池',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/landlordunit/day_210409/thumb/202104090925245858_360_480.jpg',
          width: 360,
          height: 480,
        },
        commentScore: '4.9',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·1居2床 3人 4.9分',
        showHouseVideo: false,
        cityId: 45,
        finalPrice: 373,
        location: '广州·从化区',
      },
    },
    {
      discoveryContentType: 3,
      data: {
        iconTag: null,
        productPrice: 164,
        priceTipBadge: {
          type: 0,
          text: '已减¥30',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 50196196,
        houseName:
          '芸晨落地窗投影仪复试公寓(近白云山公园，白云汇，国际单位会议中心，萧岗地铁站商圈近医院)',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/landlordunit/day_210528/thumb/202105281710367309_700_467.jpg',
          width: 700,
          height: 467,
        },
        commentScore: '4.2',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·1居1床 2人 4.2分',
        showHouseVideo: true,
        cityId: 45,
        finalPrice: 134,
        location: '广州·白云区',
      },
    },
    {
      discoveryContentType: 9,
      data: {
        iconTag: null,
        productPrice: 347,
        priceTipBadge: {
          type: 0,
          text: '已减¥33',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 41038306,
        houseName: '艾尔维轻奢雅致大床房',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/landlordunit/day_200802/thumb/202008022333308968_360_480.jpg',
          width: 360,
          height: 480,
        },
        commentScore: '4.5',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·1居1床 2人 4.5分',
        showHouseVideo: false,
        cityId: 45,
        finalPrice: 314,
        location: '广州·越秀区',
      },
    },
    {
      discoveryContentType: 9,
      data: {
        iconTag: null,
        productPrice: 937,
        priceTipBadge: {
          type: 0,
          text: '已减¥125',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 49948159,
        houseName: '【礼寓】珠江新城美领馆地铁旁的高层，艺术家庭三居美景公寓',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/landlordunit/day_210510/thumb/202105101722488310_360_480.jpg',
          width: 360,
          height: 480,
        },
        commentScore: '5.0',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·3居3床 4人 5.0分',
        showHouseVideo: false,
        cityId: 45,
        finalPrice: 812,
        location: '广州·天河区',
      },
    },
    {
      discoveryContentType: 3,
      data: {
        iconTag: null,
        productPrice: 458,
        priceTipBadge: {
          type: 0,
          text: '已减¥40',
          color: '#FFFFFF',
          background: null,
          border: null,
          orderIndex: 0,
          tip: null,
          jumpUrl: null,
          colorType: 0,
          gradient: { startColor: '#FF6666', endColor: 'FF9F9F' },
        },
        houseAdvert: null,
        activityInfo: null,
        sellingPoint: null,
        guideText: null,
        referencePriceDesc: null,
        poiLocation: null,
        houseId: 6734100,
        houseName: '《花园房》广州塔500米，顶层花园露台、投影、田园一居室',
        houseTags: null,
        image: {
          url: 'https://pic.tujia.com/upload/landlordunit/day_210710/thumb/202107101721367184_700_467.jpg',
          width: 700,
          height: 467,
        },
        commentScore: '4.9',
        extendMap: { logicBit: '2048' },
        summaryText: '整套·1居1床 2人 4.9分',
        showHouseVideo: true,
        cityId: 45,
        finalPrice: 418,
        location: '广州·海珠区',
      },
    },
  ],
}
